spring:
  datasource:
    url: jdbc:mysql://172.16.20.233:3306/elastic-job?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: payment
    password: Itsme@999
   
    